In [ ]:

import numpy as np

# 1. Create a numpy array of 1d, 2d, 3d
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(3,19,3)
arr2 = arr2.reshape(2,3)
arr3 = np.arange(1,13)
arr3 = arr3.reshape(3,2,2)

# Print results
print("1D Array:", arr)
print("\n2D Array:\n", arr2)
print("\n3D Array:\n", arr3)

DEPRECATION: Loading egg at c:\users\avnee\python37\lib\site-packages\vboxapi-1.0-py3.11.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330


Note: you may need to restart the kernel to use updated packages.
1D Array: [1 2 3 4 5]

2D Array:
 [[ 3  6  9]
 [12 15 18]]

3D Array:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# 2. Access elements of all the three arrays created
ele1 = arr[2]
ele2 = arr2[1,2] 
ele3 = arr3[1, 0, 1]

print("Accessed Element from 1D Array:", ele1)
print("Accessed Element from 2D Array:", ele2)
print("Accessed Element from 3D Array:", ele3)

Accessed Element from 1D Array: 3
Accessed Element from 2D Array: 18
Accessed Element from 3D Array: 6


In [ ]:
# 3. Perform array slicing
slice1 = arr[1:4]
slice2 = arr2[:, 1:3]
slice3 = arr3[:, 1, :]

# 4. Reshape 3d array to a 1d array
reshaped_1d = arr3.reshape(-1)

print("Sliced 1D Array:", slice1)
print("\nSliced 2D Array:\n", slice2)
print("\nSliced 3D Array:\n", slice
      3)
print("\nReshaped 1D Array from 3D Array:", reshaped_1d)


Sliced 1D Array: [2 3 4]

Sliced 2D Array:
 [[ 6  9]
 [15 18]]

Sliced 3D Array:
 [[ 3  4]
 [ 7  8]
 [11 12]]

Reshaped 1D Array from 3D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# 5. Perform array arithmetic operations
sum_array = arr + 10  
product_array = arr2 * 2  

print("Sum Array:", sum_array)
print("\nProduct Array:\n", product_array)


Sum Array: [11 12 13 14 15]

Product Array:
 [[ 6 12 18]
 [24 30 36]]


In [ ]:
# 6. Sort the array
sorted_arr = np.sort(arr)
sorted_arr2 = np.sort(arr2, axis=None).reshape(arr2.shape)

# 7. Perform matrix multiplication using n-d array and matrix class
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
matrix_product_ndarray = np.multiply(matrix_a, matrix_b)  # Using n-d array
matrix_product_matrix = np.matmul(matrix_a, matrix_b)  # Using matrix class

print("Sorted 1D Array:", sorted_arr)
print("\nSorted 2D Array:\n", sorted_arr2)
print("\nMatrix Product using n-d array:\n", matrix_product_ndarray)
print("\nMatrix Product using matrix class:\n", matrix_product_matrix)

Sorted 1D Array: [1 2 3 4 5]

Sorted 2D Array:
 [[ 3  6  9]
 [12 15 18]]

Matrix Product using n-d array:
 [[ 5 12]
 [21 32]]

Matrix Product using matrix class:
 [[19 22]
 [43 50]]
